<?php
include('header.php');
include('includes/banner.php');
include('includes/clients.php');
include('includes/product.php');
include('includes/expert-service.php');
include('includes/company.php');
include('includes/testimonial.php');
include('includes/services.php');
include('includes/get-in-touch.php');
include('includes/news.php');
include('includes/why-choose.php');
include('footer.php');
?>